### ISSUE TITLE
What is the status of the extenstion?

### ISSUE THREAD

**Issue by ieugen** [leotu/quarkus-ext-jooq#1]
Hello,

I'm looking to use jooq with quarkus and I was wondering what is the status of this extension?
Also, how can I use this extension? Is it published someplace? I have not seen it in the list of Quarkus supported extensions.

This is related to the quarkus issue to support Jooq  https://github.com/quarkusio/quarkus/issues/7440

Thanks,
Eugen

**Comment by leotu** [comment]
Plan to support quarkus 1.6.x

**Comment by leotu** [comment]
Supported & Testing Versions: Quarkus 1.6.1 + jOOQ 3.13.3
